Map<String, String> bnBD = {
  /// auth titles and subtitles.
  "Login": "লগইন",
  "loginSubtitle": "অনুগ্রহ করে আপনার ইউজার আইডি এবং পাসওয়ার্ড লিখুন",
  "Forgot Password": "পাসওয়ার্ড ভুলে গেছেন",
  'forgotPasswordSubtitle': 'পাসওয়ার্ড রিসেট করতে, অনুগ্রহ করে আপনার ইউজার আইডি লিখুন',
  'Change Password': 'পাসওয়ার্ড পরিবর্তন করুন',
  'changePasswordSubtitle': 'আপনার অ্যাকাউন্টের জন্য একটি নতুন পাসওয়ার্ড তৈরি করুন',
  'PIN Confirmation': 'পিন নিশ্চিতকরণ',
  'PINConfirmationSubtitle': 'নিরাপত্তার জন্য, আপনার প্রোফাইল পিন কোড প্রদান করুন।',
  'passChangeSuccessTitle': 'আপনার পাসওয়ার্ড আপডেট হয়েছে!',
  'passChangeSuccessSubtitle': 'ধন্যবাদ, আপনার পাসওয়ার্ড আপডেট হয়েছে। অনুগ্রহ করে পুনরায় লগইন করুন।',
  'Area Managers': 'এরিয়া ম্যানেজার',

  /// auth label texts
  'User ID :': 'ইউজার আইডি :',
  'Password :': 'পাসওয়ার্ড :',
  'User ID/ Profile ID :': 'ইউজার আইডি/ প্রোফাইল আইডি :',
  'Current Password': 'বর্তমান পাসওয়ার্ড',
  'New Password': 'নতুন পাসওয়ার্ড',
  'Confirm New Password': 'নতুন পাসওয়ার্ড নিশ্চিত করুন',

  /// buttons
  'Remember me': 'আমাকে মনে রাখবেন',
  "ForgotPassword": "ফরগট পাসওয়ার্ড?",
  'Next': 'নেক্সট',
  'Skip': 'স্কিপ',
  'Submit': 'সাবমিট',
  'Confirm': 'কনফার্ম',
  'OK, Got It': 'ঠিক আছে, বুঝেছি',
  'Contact Support': 'সাপোর্ট',
  'Area Manager': 'এরিয়া ম্যানেজার',
  'Details': 'বিস্তারিত',
  'Add': 'অ্যাড',
  'PAID': 'পরিশোধিত',
  'UNPAID': 'অপরিশোধিত',
  'Product Orders': 'পণ্য অর্ডার',
  'Client\nTransaction': 'ক্লায়েন্ট\nলেনদেন',
  'Summary Information': 'সারসংক্ষেপ তথ্য',
  'View Report': 'রিপোর্ট দেখুন',
  'Place Order': 'অর্ডার দিন',
  'Proceed to Checkout': 'চেকআউট',
  'Checkout': 'চেকআউট',
  'Order Summary': 'অর্ডার সামারি',
  'Payment': 'পেমেন্ট',
  'Done': 'সম্পন্ন',
  'Client \nTransaction': 'ক্লায়েন্ট \nলেনদেন',
  'Call': 'কল',
  'Cancel': 'বাতিল',



  /// snack bars or validations
  'Enter a valid User ID': 'একটি বৈধ ইউজার আইডি লিখুন',
  'Please enter a valid User ID.': 'অনুগ্রহ করে একটি বৈধ ব্যবহারকারী আইডি লিখুন।',
  'User ID Verified': 'ব্যবহারকারী আইডি যাচাই করা হয়েছে',
  'Verification Failed': 'যাচাই ব্যর্থ হয়েছে',
  'Proceeding to reset password.': 'পাসওয়ার্ড রিসেট করার জন্য এগোনো হচ্ছে।',
  'User ID not recognized. Please try again.': 'ব্যবহারকারী আইডি চেনা যায়নি। অনুগ্রহ করে আবার চেষ্টা করুন।',
  'Enter your password': 'আপনার পাসওয়ার্ড লিখুন',
  'Password must be at least 6 characters': 'পাসওয়ার্ড কমপক্ষে ৬ অক্ষরের হতে হবে',
  'Login Success': 'লগইন সফল',
  'You have successfully logged in.': 'আপনি সফলভাবে লগইন করেছেন।',
  'Login Failed': 'লগইন ব্যর্থ',
  'Invalid username or password. Please try again.': 'ভুল ইউজারনেম বা পাসওয়ার্ড। অনুগ্রহ করে আবার চেষ্টা করুন।',
  'Form Incomplete': 'ফর্ম অসম্পূর্ণ',
  'Please fill out all fields correctly.': 'অনুগ্রহ করে সঠিকভাবে সব ফিল্ড পূরণ করুন।',
  'Password Updated': 'পাসওয়ার্ড আপডেট হয়েছে',
  'Your password has been updated successfully.': 'আপনার পাসওয়ার্ড সফলভাবে আপডেট হয়েছে।',
  'Invalid New Password': 'অবৈধ নতুন পাসওয়ার্ড',
  'New password cannot be the same as the current password.': 'নতুন পাসওয়ার্ড বর্তমান পাসওয়ার্ডের সাথে একীভূত হতে পারে না।',
  'Incorrect Password': 'ভুল পাসওয়ার্ড',
  'The current password you entered is incorrect.': 'আপনি যে বর্তমান পাসওয়ার্ডটি প্রদান করেছেন তা ভুল।',
  'Enter your new password': 'আপনার নতুন পাসওয়ার্ড লিখুন',
  'Confirm your new password': 'আপনার নতুন পাসওয়ার্ড নিশ্চিত করুন',
  'Passwords do not match': 'পাসওয়ার্ড মেলে না',
  'Incorrect PIN': 'ভুল PIN',
  'The PIN you entered is incorrect.': 'আপনি যে PIN প্রদান করেছেন তা ভুল।',
  'Your order is placed!': 'আপনার অর্ডার সম্পন্ন হয়েছে!',
  'You can check the progress of your order in activity menu': 'আপনার অর্ডারের অগ্রগতি অ্যাক্টিভিটি মেনুতে দেখতে পারেন',


  /// labels
  'Company List': 'কোম্পানির তালিকা',
  'Home': 'হোম',
  'Dashboard': 'ড্যাশবোর্ড',
  'Company : ': 'কোম্পানি : ',
  'Categories': 'বিভাগসমূহ',
  'Most Popular': 'সর্বাধিক জনপ্রিয়',
  'Top Sales': 'সর্বাধিক বিক্রি',
  'Load More': 'আরো লোড করুন',
  'Search Products': 'পণ্য অনুসন্ধান করুন',
  'Carts': 'কার্টস',
  'Add Items': 'অ্যাড আইটেম',
  'Sub-Total': 'সাব-টোটাল',
  'Total': 'টোটাল',
  'Products': 'পণ্যসমূহ',
  'Product Details': 'পণ্যের বিবরণ',
  'Refer Product': 'পণ্য রেফার করুন',
  'Remarks': 'মন্তব্য',
  'Add Your Remarks': 'আপনার মন্তব্য যোগ করুন',
  'Transactions': 'লেনদেনসমূহ',
  'From Date': 'ফ্রম ডেট',
  'To Date': 'টু ডেট',
  'Report': 'রিপোর্ট',
  'Language': 'ভাষা',
  'Logout': 'লগআউট',
  ' Settings': 'সেটিংস',
  'Select your preferable language': 'আপনার পছন্দসই ভাষা নির্বাচন করুন',
  'Are you sure you want to proceed?': 'আপনি কি নিশ্চিত যে আপনি এগিয়ে যেতে চান?',

};
