Map<String, String> enUS = {

  /// auth titles and subtitles.
  "Login": "Login",
  "loginSubtitle": "Please enter your User ID and Password",
  "Forgot Password": "Forgot Password",
  'forgotPasswordSubtitle': 'Please, your user-id to reset the password',
  'Change Password': 'Change Password',
  'changePasswordSubtitle': 'Please create a new password for your account',
  'PIN Confirmation': 'PIN Confirmation',
  'PINConfirmationSubtitle': 'Please, your profile PIN Code for the security.',
  'passChangeSuccessTitle': 'Your password has been updated!',
  'passChangeSuccessSubtitle': 'Thanks, your password has been updated. Please, try to re-login.',
  'Area Managers': 'Area Managers',

  /// auth label texts
  'User ID :': 'User ID :',
  'Password :': 'Password :',
  'User ID/ Profile ID :': 'User ID/ Profile ID :',
  'Current Password': 'Current Password',
  'New Password': 'New Password',
  'Confirm New Password': 'Confirm New Password',

  /// buttons
  'Remember me': 'Remember me',
  "ForgotPassword": "Forgot Password?",
  'Next': 'Next',
  'Skip': 'Skip',
  'Submit': 'Submit',
  'Confirm': 'Confirm',
  'OK, Got It': 'OK, Got It',
  'Contact Support': 'Contact Support',
  'Area Manager': 'Area Manager',
  'Details': 'Details',
  'Add': 'Add',
  'PAID': 'PAID',
  'UNPAID': 'UNPAID',
  'Product Orders': 'Product Orders',
  'Client\nTransaction': 'Client\nTransaction',
  'Summary Information': 'Summary Information',
  'View Report': 'View Report',
  'Place Order': 'Place Order',
  'Proceed to Checkout': 'Proceed to Checkout',
  'Checkout': 'Checkout',
  'Order Summary': 'Order Summary',
  'Payment': 'Payment',
  'Done': 'Done',
  'Call': 'Call',
  'Cancel': 'Cancel',


  /// snack bars or validations
  'Enter a valid User ID': 'Enter a valid User ID',
  'Please enter a valid User ID.': 'Please enter a valid User ID.',
  'User ID Verified': 'User ID Verified',
  'Verification Failed': 'Verification Failed',
  'Proceeding to reset password.': 'Proceeding to reset password.',
  'User ID not recognized. Please try again.': 'User ID not recognized. Please try again.',
  'Enter your password': 'Enter your password',
  'Password must be at least 6 characters': 'Password must be at least 6 characters',
  'Login Success': 'Login Success',
  'You have successfully logged in.': 'You have successfully logged in.',
  'Login Failed': 'Login Failed',
  'Invalid username or password. Please try again.': 'Invalid username or password. Please try again.',
  'Form Incomplete': 'Form Incomplete',
  'Please fill out all fields correctly.': 'Please fill out all fields correctly.',
  'Password Updated': 'Password Updated',
  'Your password has been updated successfully.': 'Your password has been updated successfully.',
  'Invalid New Password': 'Invalid New Password',
  'New password cannot be the same as the current password.': 'New password cannot be the same as the current password.',
  'Incorrect Password': 'Incorrect Password',
  'The current password you entered is incorrect.': 'The current password you entered is incorrect.',
  'Enter your new password': 'Enter your new password',
  'Confirm your new password': 'Confirm your new password',
  'Passwords do not match': 'Passwords do not match',
  'Incorrect PIN': 'Incorrect PIN',
  'The PIN you entered is incorrect.': 'The PIN you entered is incorrect.',
  'Your order is placed!': 'Your order is placed!',
  'You can check the progress of your order in activity menu': 'You can check the progress of your order in activity menu',

  /// labels
  'Company List': 'Company List',
  'Home': 'Home',
  'Dashboard': 'Dashboard',
  'Company : ': 'Company : ',
  'Categories': 'Categories',
  'Most Popular': 'Most Popular',
  'Top Sales': 'Top Sales',
  'Load More': 'Load More',
  'Search Products': 'Search Products',
  'Carts': 'Carts',
  'Add Items': 'Add Items',
  'Sub-Total': 'Sub-Total',
  'Total': 'Total',
  'Products': 'Products',
  'Product Details': 'Product Details',
  'Refer Product': 'Refer Product',
  'Remarks': 'Remarks',
  'Add Your Remarks': 'Add Your Remarks',
  'Transactions': 'Transactions',
  'From Date': 'From Date',
  'To Date': 'To Date',
  'Report': 'Report',
  'Language': 'Language',
  'Logout': 'Logout',
  ' Settings': 'Settings',
  'Select your preferable language': 'Select your preferable language',
  'Are you sure you want to proceed?': 'Are you sure you want to proceed?',
};
